### PR TITLE
use className instead of setAttribute in IE9 (fixes #96)

### LINKED ISSUE #96: IE9 bug: literal:class has trouble
Hello. This time I'm prepared with [a Fiddle](https://jsfiddle.net/MrYeah/8b2vusea/2/). 😉

The evaluation of `literal:class` fails on some circumstances in IE9. It works well on IE11 (didn't test IE10) and other browsers.

You may have to [run it as a draft](http://doc.jsfiddle.net/basic/introduction.html#draft-page) in order to test it on IE9.

### PR DESCRIPTION
**Pull request by kaasasolut**

### CODE REVIEW

**Comment by kbrsh** [comment]
Hey! Sorry, I didn't seem to get a notification for this PR. Please follow the [commit message rules](https://github.com/kbrsh/moon/blob/master/CONTRIBUTING.md#commits).

**Comment by kaasasolut** [comment]
I can see why Moon v1 probably won't support IE9. But currently IE9 is still supported.
So in my opinion there are only two possibilities:

- Moon gets a fix for that bug.
- Moon drops the support for IE9 already.

I can live with both decisions. But I highly disagree to say that Moon supports IE9 while it contains known issues.

**Comment by kbrsh** [comment]
I feel like I should call it _partial_ IE9 support, meaning it does everything that is documented but does not take care of weird bugs in IE itself.

**Comment by kaasasolut** [comment]
Well, then it has to be documented which things do not work on IE9. Otherwise it's way too unreliable to use Moon in production. And that would be a real pity.

**Comment by yieme** [comment]
+1 IE9 support

**Comment by kbrsh** [comment]
Moon now uses property names by default, so this should be fixed.

**Pull request closed without merging**
