### PR TITLE
Update API docs

### PR DESCRIPTION
**Pull request by meyer1994**
category: docs

- Added reference entry for the constructor of instance;
- Added in-depth explanation of the options object used in the
constructor;
- Added example for the constructor;
- Changed some single quotes to double quotes in some examples to match
convention used in the code;
- Removed callMethod from docs;
- Added object use case of instance.set.

### CODE REVIEW

**Comment by kbrsh** [comment]
Awesome! :tada:

This is for the current features of v1 though, which hasn't been released yet. I think it'd be a good idea to keep the v0.11.0 documentation for now (it includes callMethod, keypath sets, and different properties on the constructors).

I'll keep this open and merge when v1 is released, thanks!

**Comment by meyer1994** [comment]
No problem! I am just trying to get some work done beforehand :)

**Comment by kbrsh** [comment]
Awesome, thanks!

**Comment by kbrsh** [comment]
Hey! [Moon v1 beta 3](https://kbrsh.github.io/moon) has a new API and I'm afraid these docs won't really work with it. Thanks for the help though, and feel free to check out the new documentation.

**Pull request closed without merging**
