### PR TITLE
Wording clarification

### PR DESCRIPTION
**Pull request by simonw**

### CODE REVIEW

**Comment by kbrsh** [comment]
Thanks for catching that! Can you please revert those changes and edit the files in `src/docs/components.md`? The docs are built from markdown.

**Comment by simonw** [comment]
Done! I have to admit, I had quite a bit of trouble figuring out how to edit your documentation - I always forget to check for a gh-pages branch. Have you considered running a separate moon-docs repo instead?

**Comment by kbrsh** [comment]
Awesome! I haven't considered a moon-docs repo, but it might be a good idea. The documentation basically works by converting all `md` files in the `src` directory and copying them to the root directory while converting them to HTML.

It would also be great if you could squash this into a single commit.

**Comment by simonw** [comment]
You can merge this into a single commit using this menu option (I use this option all the time, I love being able to turn a pull request with multiple changes into a single commit to master):

cursor_and_testing_pull_requests_by_simonw_ _pull_request__1_ _simonw_destination_search

**Comment by kbrsh** [comment]
Huh. TIL. Thanks!

**Pull request merged**
